### ISSUE TITLE
Kiosk mode, how to open the settings page?

### ISSUE THREAD

**Issue by tramas76** [PegorK/PeggyBoard#2]
Hi Pegor, after installation the raspberry starts and chromium opens with the google home page and that's it.
Do I need to indicate the opening of a page in the kiosk settings? if so which one? .....settings.php?

I'm sure I followed all the instructions.

The web server works and I reach the page but when I try to save the routes an exclamation mark appears... problem with the DB? thanks, if you can help me ;-)

**Comment by PegorK** [comment]
Hi Tramas76, 

So you have your rpi running in kiosk mode with a screen connected to it? When you setup the pi in kiosk mode did you modify the `.xinitrc` file and change the website to open to the loopback address (`127.0.0.1`) ? I just noticed the link I have to configure the pi to kiosk mode is now dead :( [this tutorial](https://blog.r0b.io/post/minimal-rpi-kiosk/) is similar to the one I had originally linked. 

If you are running into issues with saving routes then it's most likely a database issue. Did you setup your database properly so that when you run the command `DESCRIBE routes` within mysql it looks like the picture referenced in Step 4? It's very important that you match the naming & password mentioned in Step 4. If you change those you have to modify some of the other scripts.

**Comment by tramas76** [comment]
Db issue ok, now i can save the routes.

in your kiosk mode guide you had to edit the /etc/xdg/openbox/environment file by changing the KIOSK_URL variable. Now if I set the variable with http://127.0.01 I get the peggyboard screen to draw the routes instead of having the settings screen.

-----------------------------------------------------------------------------------------------------
Step 10. Change The URL
To change the URL on the Web site or app that launches, all you need to do is remote login to the pi and edit the Openbox environment file following the steps below:
•	Remote login to the pi:
•	ssh pi@touchpi64.local
•	Edit the Openbox environment file:
sudo nano /etc/xdg/openbox/environment
•	Change the KIOSK_URL to the URL of your Web app or site
•	Then to save the change, press Ctrl-o, enter, Ctrl-X.
Reboot the pi:
sudo reboot
-------------------------------------------------------------------------------------------------

If I check /var/log/nginx/error.log i find this error:

2024/10/13 11:28:50 [error] 714#714: *4 FastCGI sent in stderr: "PHP message: PHP Notice:  Object of class mysqli could not be converted to int in /var/www/html/main_backend.php on line 89 "while reading response header from upstream, client: 127.0.0.1, server: _, request: "POST /main_backend.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm.sock:", host: "127.0.0.1", referrer: "http://127.0.0.1/"

2024/10/13 13:56:24 [error] 714#714: *4 FastCGI sent in stderr: "PHP message: PHP Notice:  Object of class mysqli could not be converted to int in /var/www/html/main_backend.php on line 89"
 while reading response header from upstream, client: 127.0.0.1, server: _, request: "POST /main_backend.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm.sock:", host: "127.0.0.1", referrer: "http://127.0.0.1/"

2024/10/13 13:48:42 [error] 715#715: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare getVersion() (previously declared in /var/www/html/settings_backend.php:39)
in /var/www/html/main_backend.php on line 131" while reading response header from upstream,
 client: 127.0.0.1, server: _, request: "GET /settings.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm.sock:", host: "127.0.0.1"



Do you have any idea, where am I going wrong?

**Comment by PegorK** [comment]
My mistake, the Kiosk url should be `127.0.0.1/settings.php`

I'll try to check those errors out later, they don't look familiar.

**Comment by PegorK** [comment]
Ok I think I see what's going on. with those errors.  I believe the first two are from an outdated way of checking if the database opens and the last one I had two `getVersion()` definitions. I made a branch with some changes to `main_backend.php` and `settings_backend.php`. I HAVEN'T tried these changes yet, but I'm fairly confident it'll fix those issues.
[Here](https://github.com/PegorK/PeggyBoard/tree/pegor/issue_2/fixes) is the branch and this is the [commit](https://github.com/PegorK/PeggyBoard/commit/67d0fcae337f598f9251fcf90f7a7d65e1ef3ee6).

**Comment by tramas76** [comment]
now I get these errors:


2024/10/13 19:34:25 [error] 711#711: *3 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected token
 "else" in /var/www/html/main_backend.php on line 106" while reading response header from upstream, client: 192.168.1.14, server: _,
 request: "GET /settings.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm.sock:", host: "192.168.1.10"

2024/10/13 19:34:26 [error] 711#711: *3 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected token
 "else" in /var/www/html/main_backend.php on line 106" while reading response header from upstream, client: 192.168.1.14, server: _,
 request: "GET /settings.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm.sock:", host: "192.168.1.10"

2024/10/13 19:35:00 [alert] 711#711: *6 open socket #15 left in connection 5

2024/10/13 19:35:00 [alert] 711#711: aborting

2024/10/13 19:35:58 [error] 711#711: *1 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected token
 "else" in /var/www/html/main_backend.php on line 106" while reading response header from upstream, client: 127.0.0.1, server: _,
 request: "GET /settings.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm.sock:", host: "127.0.0.1"

**Comment by tramas76** [comment]
Just for testing I commented the "else" lines around 106....

Now the settings page opens, almost everything works, except that it doesn't show the IP address and it doesn't scan wi-fi networks. 
Yet the raspberry is connected to the wifi network via raspi-config.

**Comment by PegorK** [comment]
Ok I updated the branch, there was an accidental "else" statement. Also for the ip address and the scan did you make the `runRoot.sh` and `connectToWifi.sh` scripts executable like in step 12 and also added the `runRoot.sh` to your sudoers list that is mentioned in Step 11? The output of the command `cat /etc/sudoers` should look like this:

```
#
# This file MUST be edited with the 'visudo' command as root.
#
# Please consider adding local content in /etc/sudoers.d/ instead of
# directly modifying this file.
#
# See the man page for details on how to write a sudoers file.
#
Defaults        env_reset
Defaults        mail_badpass
Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Host alias specification

# User alias specification

# Cmnd alias specification

# User privilege specification
root    ALL=(ALL:ALL) ALL

# Allow members of group sudo to execute any command
%sudo   ALL=(ALL:ALL) ALL

# See sudoers(5) for more information on "@include" directives:

@includedir /etc/sudoers.d


%www-data ALL=NOPASSWD: /var/www/custom_scripts/runRoot.sh

```
That last line is very important, if it's not there you must add it using the command `sudo visudo`

**Comment by tramas76** [comment]
HI,
almost everything works now.
I wrote this line wrong:     %www-data ALL=NOPASSWD: /var/www/custom_scripts/runRoot.sh

I can see the wifi networks, it seems to connect.
But I can't see the IP address.
I did everything with scripts.sh and granted the rights.

Consider that I haven't mounted the touch display yet, so I have a LAN network attached to the Raspi, and I check the changes from my PC's browser on the same network. Maybe that's why I don't see the IP?

**Comment by tramas76** [comment]
ok, I'll answer myself.....I tried to connect to the phone's wifi and so I see the IP.
So EVERYTHING WORKS!
Also changing the number of LEDs and fewer lines on the Y axis.
THANK YOU VERY MUCH!!!

**Comment by PegorK** [comment]
That's great to hear!
Is your PI connected via Ethernet? The ip address retrieval command only works for when the device is on a wifi network.

**Comment by PegorK** [comment]
Oh didn't see your update. That's awesome news! Glad everything is working.
